name: Update Changelog

on:
  release:
    types: [released]

jobs:
  update-changelog:
    name: Update Changelog
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.release.target_commitish }}
          token: ${{ secrets.CHANGELOG_TOKEN }}

      - name: Extract Release Date
        id: release_date
        run: |
          echo "date=$(git log -1 --date=short --format=%ad '${{ github.event.release.tag_name }}')" >> $GITHUB_OUTPUT;

      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          release-date: ${{ steps.release_date.outputs.date }}
          release-notes: ${{ github.event.release.body }}
          latest-version: ${{ github.event.release.tag_name }}

      - name: Build Commit Message
        run: |
          echo "Update CHANGELOG" >> commitmessage.txt
          echo "[skip ci]" >> commitmessage.txt

      - name: Set Commit Message
        id: commit_message
        run: |
          echo 'commit_message<<EOF' >> $GITHUB_OUTPUT
          cat commitmessage.txt >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - name: Remove Commit Message File
        run: rm -rf commitmessage.txt

      - name: Commit Updated Changelog
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: ${{ github.event.release.target_commitish }}
          commit_message: ${{ steps.commit_message.outputs.commit_message }}
          file_pattern: CHANGELOG.md
          push_options: "--force"
