name: Code Style

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "*"

permissions:
  contents: write

jobs:
  lint:
    name: Check Code Style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, bcmath, intl, exif, iconv, fileinfo
          tools: composer
          coverage: none

      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Run Pint
        run: composer run lint

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 🪄 Code Style Fixes
