name: PHPStan

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "*"

jobs:
  phpstan:
    name: Run Static Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          tools: composer
          coverage: none

      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Run PHPStan
        run: composer run test:types
